### ISSUE TITLE
XRScene crash on iOS.

### ISSUE THREAD

**Issue by oms064** [8thwall/xr-unity#14]
Hello, hope this is the right place to ask.
I'm having issues with this plugin on iOS, on Android everything works fine. I'm using Unity 2017.2.
My issue is that when I open the scene where the XR scripts are being called the application closes. XCode breaks the execution and I see an EXC_BAD_ACCESS.

![bad_access](https://user-images.githubusercontent.com/3358495/34143638-55af6358-e453-11e7-9984-15e6791865e5.png)

The stacktrace says the error is in the function setManagedCameraTexture which is in a DLL so I can't tell what is really happening.

![screenshot](https://user-images.githubusercontent.com/3358495/34143608-2ade23bc-e453-11e7-858f-31b5e55ed20c.png)

These are my player settings:
![inkedplayer_settingspng_li](https://user-images.githubusercontent.com/3358495/34143807-3ed29d7a-e454-11e7-9c79-ca8ee5224ac7.jpg)
![player_settings2](https://user-images.githubusercontent.com/3358495/34143809-4080f7e8-e454-11e7-8b27-b0803de7b352.png)
![player_settings3](https://user-images.githubusercontent.com/3358495/34143811-41fff65a-e454-11e7-9d57-462bd5838fe2.png)

**Comment by atomarch** [comment]
Hi @oms064, I'd be happy to assist here.  If needed we can move the conversation over to support@8thwall.com, but let's start here :)

Can you share a bit more about your setup?
- What version of iOS?
- What version of XCode?
- What version of 8th Wall XR is installed? (check Assets -> XR -> 8th Wall XR and it will display version in the inspector panel)
- Are you using the various XR*Controllers provided with the plugin, or are you writing your own scripts against the functions provided in XRController.cs?
- Can you share info on your unity scene setup, and what 8th Wall XR components you are using?

Thanks!!

**Comment by atomarch** [comment]
Hello @oms064 , to recap our discussion, the current version of 8th Wall XR expects Metal on phones that support it.  I have asked engineering to look into adding OpenGL support on Metal phones in a future release.

**Comment by yosun** [comment]
OpenGL support is needed due to how the only Unity iOS video recording solution requires it - maybe you guys can contribute to that project https://github.com/ThisNetWorks/iVidCapPro

**Comment by atomarch** [comment]
OpenGL support for iOS was added in R5.  

See: https://docs.8thwall.com/#changelog
