### ISSUE TITLE
Camera Rendering Issues Pixel C Tab

### ISSUE THREAD

**Issue by agmcroberts** [8thwall/xr-unity#15]
Good Afternoon

I am trying to execute the demo project on a pixel c tablet to test the older device functionality with the API.  Unfortunately, there seem to be some issues with the camera rotation and display.  It seems that the display is not properly configured to fit the device, any recommendations?  Also when I look the device orientation to portrait the camera issue goes away although a new issue appears, the camera feed it rotated 90 degrees. 
![screenshot_20171219-100744](https://user-images.githubusercontent.com/26221752/34152139-72bdafca-e4a5-11e7-826a-792a165b89a8.png)
![screenshot_20171219-100736](https://user-images.githubusercontent.com/26221752/34152140-72d7a9fc-e4a5-11e7-9c0b-6492369f6f1b.png)

**Comment by atomarch** [comment]
Hi @agmcroberts , thanks for reporting this issue.  We haven't seen behavior like this, but will get our hands on a Pixel C and investigate.

**Comment by atomarch** [comment]
We have reproduced this on the Pixel C and will work on a fix.

**Comment by atomarch** [comment]
Hello @agmcroberts, a fix for this issue has been included with R5.  Please let us know if you continue to experience issues on this device.  Thanks!
