### ISSUE TITLE
Active a surface only after touching it

### ISSUE THREAD

**Issue by smtabatabaie** [8thwall/xr-unity#16]
Hi, Thanks very much for sharing this great project. I wanted to ask if it is possible to click on a surface and make it the active surface and place the gameobject on the position of the click. Kinda like ARKit which only augments the gameobject after clicking on it.
Thanks

**Comment by atomarch** [comment]
Hi @smtabatabaie - Yes, this is definitely possible.  I've added a script ([PlaceObject.cs](https://github.com/8thwall/xr-unity/blob/master/scripts/PlaceObject.cs)) to this repo that allows you to tap and place an object in your scene.  If your tap hits a surface, the object will be placed on the surface.  If not, it will be placed in the "air" at the tap point at a specified distance in front of the camera.  If this isn't exactly what you need, you can use it as a starting point and customize for your specific needs.

**Comment by smtabatabaie** [comment]
Thanks very much @atomarch , really appreciate your help, works perfectly.
