### ISSUE TITLE
Problem with Landscape Left IOS App

### ISSUE THREAD

**Issue by JPSoftservice** [8thwall/xr-unity#18]
Hello. If compile by Unity IOS app with LANDSCAPE LEFT only or AUTOROTATE - app working incorrect..
Can i fix that?

**Comment by atomarch** [comment]
Hello @JPSoftservice , thank you for contacting us.  Currently Portrait mode is supported.  We are planning to add support for landscape mode in an upcoming release, likely towards the end of Q1 2018.<sup>1<sup>

--

<sup>1<sup> The preceding is intended to outline our general product direction. It is intended for information purposes only, and may not be incorporated into any contract. It is not a commitment to deliver any material, code, or functionality, and should not be relied upon in making purchasing decisions. The development, release, and timing of any features or functionality described for 8th Wall’s products remain at the sole discretion of 8th Wall, Inc.

**Comment by yosun** [comment]
I cannot believe you guys got 10 million and cannot even support landscape mode.

**Comment by D3m0n92** [comment]
End of Q1 2018.1? Landscape mode is the first problem to solve, fast.

**Comment by jonarnold** [comment]
I look forward to this feature

**Comment by erikmchut** [comment]
Landscape mode is available in 8th Wall XR Release 6. 

It's now in public beta. If you would like to use it right now, see the following documentation on switching to the beta channel: https://docs.8thwall.com/#switching-channels

**Comment by atomarch** [comment]
Landscape mode added to Release 6 - released last week.
