### ISSUE TITLE
Devices list

### ISSUE THREAD

**Issue by bakalarczuk** [8thwall/xr-unity#24]
Hi, 
is there any list of supported devices?
I think it doesn't work on my Lenovo K6 Note

**Comment by atomarch** [comment]
Hi @bakalarczuk , can you provide more detail on the issues are you experiencing with the Lenovo K6 Note?  Screenshots or a link to a video would be helpful.

In general, we expect any device running Android Kitkat (4.4) or higher to work.  The device minimally needs to have a camera and accelerometer.  In Release 5 we added support for Android phones without gyroscopes.

Requirements: https://docs.8thwall.com/#requirements

**Comment by bakalarczuk** [comment]
Sure.
I've made demo with steps like in README file here.
And it look like doesn't recognize ground. Video here: https://drive.google.com/open?id=1q_CNc2GDvp2iOHjPwgFEROzvHJertX39

**Comment by bakalarczuk** [comment]
Hi there,
maybe problem is Unity version? I used 2017.3.0p4
I'll try to compile your demo and give you a feedback

**Comment by bakalarczuk** [comment]
Is it possible, that your library needs to enable ARCore or ARKit compatibility?

**Comment by bakalarczuk** [comment]
Step by step I'm getting things to work. If it is any method to "see" surface on device screen in my Lenovo K6 Note?

**Comment by atomarch** [comment]
Hi @bakalarczuk , [this script](https://github.com/8thwall/xr-unity/blob/master/scripts/MeshVisualizer.cs) can be used to visualize the mesh of an object.  

True surface detection is currently supported on ARKit/ARCore phones.  See [here](https://docs.8thwall.com/#requirements) for features supported by platform.  For Non-ARKit/ARCore devices, fixed surfaces are provided.  We assume that the gameobject (e.g. Plane) that has the XRSurfaceController attached is at height zero (y=0).  To get an idea of how it will look on your device, select the main cam and look at your game view.

If you want to determine what features are available to a given device at runtime, you can query the [XRCapabilities API](https://docs.8thwall.com/#xrcapabilities).

**Comment by bakalarczuk** [comment]
So, if I understood correctly, I need to create a fkat plane at, let's say, Vector3.zero with XRSurfaceController on it, and than I can place, for example, table with TV on that "simulated" surface on Non-ARKit/Core devices, like my Lenovo, right?
