### ISSUE TITLE
error at update

### ISSUE THREAD

**Issue by irfanyusuf** [8thwall/xr-unity#35]
Hi,, I update my 8thwall plugin from editor and get error when I run it.

DllNotFoundException: XRStreamingPlugin
XRInternal.XRNativeBridge.XRGetEnvironment () (at Assets/XR/Scripts/XRNativeBridge.cs:402)
XRInternal.XRNativeBridge.GetXREnvironment () (at Assets/XR/Scripts/XRNativeBridge.cs:613)
XRController.Awake () (at Assets/XR/Scripts/XRController.cs:485)

How can I fix this?

**Comment by erikmchut** [comment]
@irfanyusuf thank you for reporting this. The issue is caused by missing DLLs in the R6 release for Unity for Windows, and we're planning to push a R6.1 release this morning that will remedy this problem. We'll send a follow-up note here when the update is available.

**Comment by erikmchut** [comment]
Release 6.1 is now available which should resolve this issue. Within Unity, from the top menu, select XR > Check for Updates. Thanks for catching this.

**Comment by irfanyusuf** [comment]
it fixed, thx for fast support!
