### ISSUE TITLE
Feature: Ability to disable / enable XR

### ISSUE THREAD

**Issue by GimpMaster** [8thwall/xr-unity#40]
My application uses AR for just a small portion of the app. It would be nice if you provided a static method that would disable/re-enable XR.

**Comment by GimpMaster** [comment]
I've tried multiple ways of disabling XR but none of which is really working. For example I've tried disabling the game objects XRController, XRSurface, and disabling the two components on the camera. Then during the time I need to I enable them but this doesn't seem to work. 

I've tried other hacks such as waiting for the first second of the app and then disabling, then trying to re-enable.

Any other suggestions?

**Comment by atomarch** [comment]
Hi @GimpMaster, this is a great suggestion and I'll ask engineering to look into exposing some of the underlying lifecycle management functions.  Currently, most of our customers use Unity's scene management features to handle this, i.e. switch to a different scene (containing your XRController, XRSurfaceController, etc) using [SceneManager.LoadScene()](https://docs.unity3d.com/ScriptReference/SceneManagement.SceneManager.LoadScene.html) when you need to use the AR features, and then switch back when done.  We do this in our own [XR Remote app](https://docs.8thwall.com/#remote-overview).  If you need to handle data between scenes, I've found [this article](https://gamedev.stackexchange.com/questions/110958/unity-5-what-is-the-proper-way-to-handle-data-between-scenes) to be helpful.  Please let me know if this helps. Thanks!

**Comment by GimpMaster** [comment]
Thank you Tony. That is a good suggestion. I thought another method might be to have two cameras and enable/disable them, but I would also want the tracking disabled as well. I think the ARKit has a pause() function.

**Comment by mralbean** [comment]
We added [Pause()](https://docs.8thwall.com/#xrcontrollerpause), [Resume()](https://docs.8thwall.com/#xrcontrollerresume) and [IsPaused()](https://docs.8thwall.com/#xrcontrollerispaused) functions to the XRController API back in Release 9.0. I believe this should help!
