### ISSUE TITLE
XR Remote works intermittently

### ISSUE THREAD

**Issue by GimpMaster** [8thwall/xr-unity#43]
I'm not sure how best to describe this but let me try....

I'm using 8th wall version 7.0 on Unity 2017.4.3f1 LTS and the latest XR remote. This is running on Windows 10 with a Samsung S7 phone with USB debugging.

Sometimes I can get the remote to function as expected. I see "semi" hi-resolution imagery in the game window in unity along with video window on the phone. However most of the time I see the scene environment in the game window as well as the scene environment on the phone. What I mean by that is I see no camera video feed.

This is using the tutorial scene demo, not just my own scene. If I build to the phone everything works as expected. However the delay for testing is long as you know since it needs to build and load.

When it does begin to work I don't know what I did to make it work unfortunately. Do you have anything else you want to to inspect?

**Comment by atomarch** [comment]
Pasting the URL from your other issue into this thread...

Here is a video showing the issue: https://www.dropbox.com/s/kae4s0ar9dg0rmu/xrremote.MOV?dl=0

**Comment by GimpMaster** [comment]
Any thoughts on this? One thing I did notice is that the game window in unity I can change aspect ratio and that does affect what is shown on the screen. Is there any particular settings for aspect ratio in the Unity Editor Game window?

**Comment by dattanchu** [comment]
In the video, I can't tell if your MainCamera has XRCameraController. It would explain why when you move your phone, the camera would not move. But you mentioned that everything works on when built on the device so this is unlikely to be the problem.

RE: aspect ratio. When the device connects, Unity will try to set your aspect ratio to an XR Remote aspect ratio reflecting the Default Orientation settings of your project. i.e. if your default orientation is Portrait, you should see your Editor Game Window auto-set to XR Remote with a Portrait aspect ratio.

Have you tried restarting the computer? If you restart the computer and everything works for a short period and then stops working, it is likely you are running into connection issue on adb. If this is your issue, you can kill adb and run it manually in a window before starting Unity. 

Another way to circumvent the adb issue is to use our network connection. You need to install Bonjour on your Windows device and your wifi needs to allow mdns.

**Comment by GimpMaster** [comment]
@dattanchu Funny thing is before I read this I thought the same so I killed my adb server and restarted it and it's back to working. 

On the network connection front I've found that it never connects. Most likely the MDNS. Is performance as good or better with Wifi?

**Comment by atomarch** [comment]
Hi @GimpMaster, re: USB - I'm glad to hear that restarting adb did the trick for you.  This has been added to the troubleshooting section of our docs.

https://docs.8thwall.com/#xr-remote-on-android-not-connecting-via-usb

**Comment by mralbean** [comment]
Re: connection issues over wifi - we recently identified and fixed a connectivity issue with XR remote on Windows. Updating to the latest version (8.1.1.216) should resolve your issue.
