### ISSUE TITLE
Event when XRSurface is placed

### ISSUE THREAD

**Issue by GimpMaster** [8thwall/xr-unity#44]
Is there an event or some sort of status when the XRSurface in the scene is placed? From what it looks like the XRSurface starts very far away from the camera and when a plane is detected it moves it back to it's original location.

I would like to know when that happens so I can rotate it so that it is always facing towards the camera when it initially gets placed. Thanks for the advice.

**Comment by GimpMaster** [comment]
Here is a video showing the issue https://www.dropbox.com/s/kae4s0ar9dg0rmu/xrremote.MOV?dl=0

**Comment by atomarch** [comment]
You are correct with how XRSurfaceController.cs currently works.  If "display immediately" is off, then it will move the gameobject with XRSurfaceController far away until a surface is detected.  If you don't want that behavior, you turn "display immediately" on.  In that case the initial position of the game object will be as it appears relative to the camera (check the camera preview to see how things will initially appear).  If/when a surface is detected, the object will be adjusted.

Here is a code snippet I've used in the past to that uses a Coroutine to poll and wait for a surface, let me know if this helps:

```csharp
bool surfaceFound = false;

  void Start () {
#if UNITY_EDITOR
    // We always have a surface in the Editor
    surfaceFound = true;
#endif

    StartCoroutine(CheckDetectedSurface());
  }


  IEnumerator CheckDetectedSurface() {

    while (!surfaceFound) {
      Mesh mesh = xr.GetSurface(xr.GetActiveSurfaceId()).mesh;
      if (mesh || xr.GetCapabilities().IsSurfaceEstimationFixedSurfaces ()) {
        surfaceFound = true;
      } else {
	// keep waiting, no surface detected yet
        yield return new WaitForSeconds (0.25f);
      }
    }
    if (surfaceFound) {
      // surface found, stop the Coroutine
      yield break;
    }
  }
```

You could put your logic to rotate the object towards the camera in the "if (surfaceFound)" block at the bottom, perhaps something like this:

```csharp
Vector3 cameraPos = Camera.main.transform.position;
// Rotate to look at camera position, keep Y constant (don't look up/down)
Vector3 lookPosition = new Vector3(cameraPos.x, transform.position.y, cameraPos.z);
transform.LookAt(lookPosition);
```

**Comment by GimpMaster** [comment]
Thank you. That is basically how I figured but did not know about the xr.GetSurface and didn't know if there was a better way.
