### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by GimpMaster** [8thwall/xr-unity#45]
Is there any special settings you use to increase performance? When I compare my simple test with a single cube to a AR game on the Google Play store I feel like my simple app is more jittery. Any suggestions?

**Comment by dattanchu** [comment]
By performance, do you mean the tracking performance (i.e. object stickiness to the ground) vs cpu performance (i.e. xr spends too much cpu cycle and your app is now running at an unacceptable fps)?

For tracking performance, two AR apps (one using 8th Wall and one using ARCore/ARKit) on the same phone, you should observe the same tracking performance. One AR app on different phones, the tracking performance will depend on what tracking engine is used under the hood.

For cpu performance, a simple cube in Unity on a XR Surface Controller should be able to run at a decent frame rate. Which AR game app are you comparing against? I assume this is on your Samsung S7? Which version of Android and ARCore do you have installed?

**Comment by GimpMaster** [comment]
Sorry @dattanchu that I haven't respond to this issue in a while. I've picked up the AR code once again. The game that I was comparing it to was Jenga AR. The old block game. Their game runs super smooth. 

The camera video is not jumpy as when I run a simple 8th Wall demo. I always feel when running 8th wall that the FPS drops significantly. I wish I could give you more details as subjective as I can.

I think I might try to get ARCore working in Unity and do a simple block test and compare performance to 8th wall. I understand what you are saying that 8th wall just passes the calls down to ARCore but this just seems way slower than it should be.

Maybe there is some release, compiler optimization options I should be running.

Android version: 7.0
ARCore Version 1.3.180604066

Would it help if I recorded some videos?

**Comment by dattanchu** [comment]
A recorded video would definitely help. We do test internally on Samsung S7, S8, S9 (and many more from other brands). I have not seen sub-30 fps on newer phones. By 8th Wall demo, do you mean the TV demo? Do you observe the same jumpiness when you try one of our published apps? https://play.google.com/store/apps/details?id=com.the8thwall.Viewer

**Comment by GimpMaster** [comment]
Yes the TV demo. I didn't know you had published demos. I will try those.

Unfortunately I work on this project only at night. So I will get back to you this evening.

I will also make a recording.

**Comment by GimpMaster** [comment]
@dattanchu . It turns out my issue was I was updating some UI text every frame which caused significant slowdown. Closing...
