### ISSUE TITLE
Camera rendering pink

### ISSUE THREAD

**Issue by sabbirkuasha** [8thwall/xr-unity#46]
After following every steps from 8th wall tutorial when i bulid the app it ask for camera access then just a pink screen. I read the previous issue and tried everything but non of those worked for this.
I am using samsung Note 5 
I have xr controller in my scene and enable camera is active 
my camera have to script Camera controller and video Controller 
I disabled multithread rendering from player setting 
![camera](https://user-images.githubusercontent.com/6649698/40741795-320fbf10-646e-11e8-90e9-a462929a8748.PNG)
![player settings](https://user-images.githubusercontent.com/6649698/40741796-325362e2-646e-11e8-8bcd-99719346f97a.PNG)
![xr settings](https://user-images.githubusercontent.com/6649698/40741797-32943e5c-646e-11e8-9c1b-458afb2780b5.PNG)

**Comment by mralbean** [comment]
Hi @sabbirkuasha , I’d be happy to help here!

  Could I get a bit more information on your setup? This will help us debug why your camera may not be rendering correctly.   

1) What version of XR are you using? You can find this by navigating to Assets -> XR in your Unity project and clicking on 8thWallXR. You should then see the version on the Inspector window on the sidebar. 
2) What version of Android is your device running? 
3) Can you run `adb logcat`, run your application, and copy-paste the logs here for further analysis?

  Thanks!

**Comment by sabbirkuasha** [comment]
thanks, mralbean for your reply
1. I used both xr 7.1 & 7.0 but each time end up with the same problem 
2. I am using Galaxy Note 5 with Noughat 
3. I don't have any idea about adb logcat but I am trying to run it, I will post the analysis soon

**Comment by sabbirkuasha** [comment]
@mralbean here is the adb logcat result
[mylogfile.txt](https://github.com/8thwall/xr-unity/files/2063364/mylogfile.txt)

**Comment by mralbean** [comment]
Thanks!

I'm seeing some exceptions thrown when trying to initialize an instance of ARCore. Your device, however, isn't one of the [support devices](https://developers.google.com/ar/discover/supported-devices). 

By any chance did you manually install an ARCore APK onto your device? You can check this by going to your device settings, then navigating to the Apps section, and then checking if ARCore is installed.

If ARCore is installed, uninstalling the APK should then get the demo app into a functioning state with our 8th Wall 6DoF tracker.

**Comment by sabbirkuasha** [comment]
@mralbean 
You are a genius brother, I did install arcore, after I uninstall it's now working 
Thanks a lot

**Comment by mralbean** [comment]
Great! Glad to hear this is working now!
