### ISSUE TITLE
Place object script create multiple clone 

### ISSUE THREAD

**Issue by sabbirkuasha** [8thwall/xr-unity#48]
I used the place[ PlaceObject.cs ](https://github.com/8thwall/xr-unity/blob/master/scripts/PlaceObject.cs) script but it creates several clone objects on each touch. 

Also, I tried to implement [DragAlongSurface.cs](https://github.com/8thwall/xr-unity/blob/master/scripts/DragAlongSurface.cs) script but it's not working (Probably I put it on the wrong surface)

**Comment by atomarch** [comment]
Hi @sabbirkuasha , can you please elaborate a bit more on your PlaceObject.cs issue?  This simple example script is working as designed - If your tap hits a surface, an object is spawned on the surface at that point.  It tap doesn't hit surface, create in "air" at touch point in front of camera at a distance of distanceFromCamera.  Each tap instantiates the specified prefab.  You are certainly welcome to make a copy of the script and modify if if you would like different behavior.

Regarding DragAlongSurface.cs, I would check the following:
- make sure that DragAlongSurface.cs is attached to the game object you wish to move, not the "surface" game object itself (i.e. 3D Plane with XRSurfaceController.cs attached)
- game object should have a collider
- The GameObject with an XRSurfaceController attached should be on layer "Surface"

Please let me know if this helps.
Thanks!

**Comment by sabbirkuasha** [comment]
@atomarch The DragAlongSurface.cs is working now after I added a collider on the Surface layer, thanks a lot for the quick reply

but ThePlaceObject.cs is cloning multiple object for each touch 
![capture](https://user-images.githubusercontent.com/6649698/40997474-a7a9ef04-6926-11e8-905f-2cd71e666d81.PNG)
I added ThePlaceObject.cs on a plane which already containing xrsurfacecontroller 
![setup](https://user-images.githubusercontent.com/6649698/40997581-06de72b0-6927-11e8-966d-57f1e8fb928e.PNG)

**Comment by atomarch** [comment]
Hi @sabbirkuasha, I just tried to reproduce and wasn't able to.  I have a 3D Plane game object just like you, with both an XRController and PlaceObject.cs script attached, also using the Table as the specified prefab.  Tapping only spawns one table.  I wonder if there are other game objects in your scene that also have PlaceObject.cs attached? Next, when I added PlaceObject.cs to multiple game objects in my scene, I do see a table instantiated for every copy of the script in my scene.  Let me know if this helps. Thanks!

**Comment by atomarch** [comment]
@sabbirkuasha Also, from your screenshot I notice that the Plane is on the "Default" Layer.  For these two scripts to work properly without modification, you'll want the Plane on a layer called "Surface"

**Comment by atomarch** [comment]
Closing.  If you are still experiencing an issue, please re-open

**Comment by RomeoDar** [comment]
I Have a query related to placeobject
how to use Table as the specified prefab in PlaceObject.cs (i'm using this script cube are displaying but i want to display table) and i dont want multiple object (cude or table) to be displayed in the scene as i tap on the screen, all i want is whenever i tap on the screen only one table will be displayed and also i want to move the position of that table, adjust size of table etc on the run time...please guide me or provide me code how to achieve this goal ?
