### ISSUE TITLE
Preview Crashes Unity

### ISSUE THREAD

**Issue by thePostFuturist** [8thwall/xr-unity#50]
Running a Pixel 1 with a config instructed by the tutorial.

**Comment by dattanchu** [comment]
I was able to get it working on my Pixel 1 running Oreo with ARCore installed following the instructions in the tutorial.

* Can you try re-running the tutorial app but with adb logcat running on your computer to capture the log?
* Can you provide your Android version and your installed ARCore version (if any)?

**Comment by atomarch** [comment]
Closing.  Please re-open if you are still experiencing an issue.
