### ISSUE TITLE
Does the 8thwall system utilize stereo camera?

### ISSUE THREAD

**Issue by Thaina** [8thwall/xr-unity#60]
Since stereo camera could provide depth perception in some degree I wish I could find AR framework that utilize it to use in my project

If your system already support depth texture then I would like to know which API I could use to access depth texture, then I would start using 8thwall instead of ARCore

**Comment by mralbean** [comment]
8th Wall XR does not provide an API for stereo camera usage. However, we do leverage ARCore for any devices that support it.
