### ISSUE TITLE
XR Remote connectivity issue

### ISSUE THREAD

**Issue by AquaDev86** [8thwall/xr-unity#61]
I can't stream to my Iphone x. My Computer name does show up on "Connect to:" list but when i select it this appears on phone "Cec T ComputerName". Im using unity 2017.3.1f1, ios 11.4.1 on my iphone x and using demo sample scene. Any help would be appreciated.

**Comment by atomarch** [comment]
Hi @AquaDev86 , have you tried completely turning off the Windows firewall?

**Comment by atomarch** [comment]
Also, please make sure you are running the latest version of 8th Wall XR (8.1.1.216), which fixed connection issues with XR Remote on Windows.

**Comment by AquaDev86** [comment]
Thank you so much disabling firewall worked out well.

**Comment by atomarch** [comment]
Great! Glad that helped.  Just added a section to the troubleshooting section of our docs: https://docs.8thwall.com/#xr-remote-wont-connect-over-wifi
