### ISSUE TITLE
Can't compile on xcode

### ISSUE THREAD

**Issue by AquaDev86** [8thwall/xr-unity#67]
So i made an app and it was working flawlessly on remote and then i wanted to compile it to my iphone but xcode always throws a error which is this:  ld: symbol(s) not found for architecture arm64

**Comment by atomarch** [comment]
@AquaDev86 , What version of XCode do you have installed?  Also, it would be helpful if you could provide more details on the specific errors you are receiving in XCode - code snippets or screenshots helpful. Thanks!

**Comment by atomarch** [comment]
Hi @AquaDev86, and details you can share to help us resolve your issue?

**Comment by atomarch** [comment]
Hi @AquaDev86 , going to close this issue for now.  If you are still having problems, please re-open with additional information.
