### ISSUE TITLE
Mobile camera view is not rendering

### ISSUE THREAD

**Issue by sarfarazh** [8thwall/xr-unity#7]
I exactly followed xr-unity guide on setting up the demo scene. When I run the app for first time it asks for camera access. But even on allowing, it doesn't render the camera view.

**Screenshot**
![screenshot_2017-08-30-14-41-16-468_com ruyahdigital xr0ne](https://user-images.githubusercontent.com/5380931/29864961-d9da5b10-8d91-11e7-8819-d340d36eb793.png)

Note: I'm a newbie in unity and have just started experimenting with VR/AR. So, I might have missed something that's not mentioned in xr-unity guide.

**Comment by atomarch** [comment]
Hi @sarfarazh, thanks for reaching out.  A few questions and things to check:

1. What version of Unity are you running? (and what OS?)
2. What type of phone are you using and what is the OS version?
3. Do you have an XRController object in your scene (GameObject menu -> XRController), and is it's tag set to XRController? (8th Wall XR should configure the tag for you automatically)
4. Select your XRController game object. In the inspector you should see an "XR Controller (Script)" attached. Make sure "Enable Camera" is checked.
5. Under Edit -> Project Settings -> Graphics, scroll down towards the bottom of the GraphicsSettings inspector, and under "Always Included Shaders" you should see "Unlit/XRCameraShader" (8th Wall XR also should automatically configure this for you)

Let me know if this helps.
Thanks!

**Comment by wilk3ns** [comment]
Hi, try disabling Multithreaded Rendering. It should work.
![untitled](https://user-images.githubusercontent.com/2451273/29894764-9b36735c-8de7-11e7-9036-001c1d03ef9d.png)

**Comment by atomarch** [comment]
@sarfarazh did @wilk3ns suggestion resolve the issue for you?  If not, please let us know.

**Comment by sarfarazh** [comment]
Yes @atomarch, @wilk3ns suggested worked. The camera is rendering now. But there's a new issue. 

I want the model to render on a surface. So I have attached the surface controller to the table. But it's floating.

I tried attaching the controller on a plane and then making the table a child of the plane object. It still floats.

Another strange thing..the camera renders 4 scenes instead of just one.  When I turn the camera around me, I see one scene in the front, one behind me and other two on my left and right.

**Comment by atomarch** [comment]
Native surface detection is currently supported on ARKit-enabled phones.  For older Android and iOS phones, 8th Wall XR currently provides fixed surfaces in four directions around the camera. These will appear parallel to flat surfaces around you (tables and floors) and can be used to give the appearance that an object is resting on a surface even without native surface detection.

You can see which features are supported on each platform here in the documentation:

https://docs.8thwall.com/xr/unity/#requirements

8th Wall's is actively working on adding support native surface detection for these platforms.  Unity projects using 8th Wall XR will automatically gain support for newly released features as they are made available**

(**Disclaimer: Future-looking statements here are intended to outline our general product direction. It is intended for information purposes only, and may not be incorporated into any contract. It is not a commitment to deliver any material, code, or functionality, and should not be relied upon in making purchasing decisions. The development, release, and timing of any features or functionality described for 8th Wall’s products remain at the sole discretion of 8th Wall, Inc.)

**Comment by sarfarazh** [comment]
Ok. Get it. Let me try what I can build with it.

Thanks for the help. Good luck!

**Comment by guillaume--** [comment]
hi

I am getting a similar issue (except I can't even see the TV, I suspect tracking is not working either).

    What version of Unity are you running? (and what OS?)
5.6.3p4
    What type of phone are you using and what is the OS version?
huawei mt7-L09 (android 4.4.2) and samsung galaxy note pro (android 5.0.2)

    Do you have an XRController object in your scene (GameObject menu -> XRController), and is it's tag set to XRController? (8th Wall XR should configure the tag for you automatically)
yes I do

    Select your XRController game object. In the inspector you should see an "XR Controller (Script)" attached. Make sure "Enable Camera" is checked.
checked

    Under Edit -> Project Settings -> Graphics, scroll down towards the bottom of the GraphicsSettings inspector, and under "Always Included Shaders" you should see "Unlit/XRCameraShader" (8th Wall XR also should automatically configure this for you)
shader 6 is missing
 
thanks for your help

**Comment by atomarch** [comment]
Hi @guillaume-- , thanks for reporting this.  I was able to reproduce on a Nexus 4 running Android 4.4.3.  The same device running Android 5.1.1 worked fine.  Also, an HTC One M8 running Android 5.0.1 worked fine.   Engineering has investigated and determined that this affects Android devices below API 22 related to the new AutoFocus support added in 8th Wall XR Release 7.  A fix has been created.  I'll update you once the fix has been released.  Thanks!

**Comment by atomarch** [comment]
Hi @guillaume-- we have released a fix for this issue, and it's currently available on our beta channel (R7.1).  How to switch channels:

https://docs.8thwall.com/#switching-channels

Please let me know if your issue is resolved after updating.  Thanks!

**Comment by sabbirkuasha** [comment]
I did everything but yet my phone camera is rendering pink. um using galaxy note 5

camera 
![camera](https://user-images.githubusercontent.com/6649698/40739926-3fe79b58-6469-11e8-96bd-0deaa6db4064.PNG)

xr setting 
![xr settings](https://user-images.githubusercontent.com/6649698/40739984-660fb50e-6469-11e8-8498-f58766dd1383.PNG)

player setting 
![player settings](https://user-images.githubusercontent.com/6649698/40739991-6c8aba0a-6469-11e8-8a77-865f91132ac7.PNG)

**Comment by dnnkeeper** [comment]
> I did everything but yet my phone camera is rendering pink. um using galaxy note 5
> 
> camera
> ![camera](https://user-images.githubusercontent.com/6649698/40739926-3fe79b58-6469-11e8-96bd-0deaa6db4064.PNG)
> 
> xr setting
> ![xr settings](https://user-images.githubusercontent.com/6649698/40739984-660fb50e-6469-11e8-8498-f58766dd1383.PNG)
> 
> player setting
> ![player settings](https://user-images.githubusercontent.com/6649698/40739991-6c8aba0a-6469-11e8-8a77-865f91132ac7.PNG)

+1 I'm having pink screen in Demo project on Galaxy Note 5. 

adb logcat is full of errors:
` NullReferenceException: Object reference not set to an instance of an object
09-15 22:41:03.123 21592 21644 E Unity   :   at XRInternal.XRNativeBridge.XRGetCurrentReality () [0x00008] in D:\Downloads\8thWallXR-Demo\Assets\XR\Scripts\XRNativeBridge.cs:198
09-15 22:41:03.123 21592 21644 E Unity   :   at XRInternal.XRNativeBridge.GetCurrentRealityXR () [0x00002] in D:\Downloads\8thWallXR-Demo\Assets\XR\Scripts\XRNativeBridge.cs:673
09-15 22:41:03.123 21592 21644 E Unity   :   at XRController.GetCurrentReality () [0x00031] in D:\Downloads\8thWallXR-Demo\Assets\XR\Scripts\XRController.cs:1054
09-15 22:41:03.123 21592 21644 E Unity   :   at XRController.GetCameraPosition () [0x00002] in D:\Downloads\8thWallXR-Demo\Assets\XR\Scripts\XRController.cs:137
09-15 22:41:03.123 21592 21644 E Unity   :   at XRCameraController.Update () [0x00036] in D:\Downloads\8thWallXR-Demo\Assets\XR\Scripts\XRCameraController.cs:36`

**Comment by brookman** [comment]
@dnnkeeper I had the same error and found that the app was missing the camera permission and also doesn't request it automatically upon the first start. Granting the permission manually (via app info) fixed the error for me.

**Comment by atomarch** [comment]
@brookman Yes, this is something that Unity changed in version 2018.3 - Android apps no longer automatically ask for permissions.   Details here: https://docs.8thwall.com/xr/#unity-2018-doesnt-ask-for-android-camera-permissions

**Comment by dmaniyar** [comment]
I am getting a blank white screen after making the app. 
Shader 6 is missing but I do not know what to do. Any help would be appreciated.

**Comment by mralbean** [comment]
@dmaniyar What device are you running on? What OS and OS version? Are there any error logs that are printed when this occurs?

**Comment by Priyanshu-CODERX** [comment]
I am not able to render the camera. After build when I am running the app the background is totally black. There 2 shader's XRCameraRGBAShader & XRCameraYUVShader. I am using Unity 2019.4.18f1. Please guide me how to fix this issue.
