### ISSUE TITLE
mobile camera rendering doesn't work..

### ISSUE THREAD

**Issue by EunjeYu** [8thwall/xr-unity#70]
Hello, 8thwall! i have some question. 
i use unity version  2018.1.6f1(64bit) and ios version, 11.4. 
but, after build, i can see only default unity scene. 

I checked all below things.
---------------------------------------------------------------------------------------------------
What version of Unity are you running? (and what OS?)
What type of phone are you using and what is the OS version?
Do you have an XRController object in your scene (GameObject menu -> XRController), and is it's tag set to XRController? (8th Wall XR should configure the tag for you automatically)
Select your XRController game object. In the inspector you should see an "XR Controller (Script)" attached. Make sure "Enable Camera" is checked.
Under Edit -> Project Settings -> Graphics, scroll down towards the bottom of the GraphicsSettings inspector, and under "Always Included Shaders" you should see "Unlit/XRCameraShader" (8th Wall XR also should automatically configure this for you)
---------------------------------------------------------------------------------------------------
and 
my build setting - multithreaded Rendering ==> unenabled.  ok. 

wmmm.. what is the problem?

**Comment by atomarch** [comment]
Hi @EunjeYu , can you elaborate a bit more on what is meant by "default unity scene"?  If you have multiple scenes in your Unity project, perhaps your AR scene isn't added to the list of "Scenes in build" under File -> Build Settings.

**Comment by atomarch** [comment]
See https://docs.unity3d.com/Manual/BuildSettings.html for instructions on adding scenes to your build

**Comment by EunjeYu** [comment]
unfortunately, that's not my problem.."default unity scene" means, my iphone mobile screen show only unity scene, not mobile camera view.

**Comment by mralbean** [comment]
Perhaps some screenshots of your project setup will help debug this issue. Please answer the following questions with screenshots of your own.

Could you please navigate to `File > Build Settings > iOS`? You should make sure that you have the `Main` scene selected and any other scenes deselected:
![screen shot 2018-09-09 at 7 04 30 pm](https://user-images.githubusercontent.com/2483955/45272643-49ef9480-b463-11e8-8a47-4a0abce9ee64.png)

Next, let's check that the scripts on the scene are setup properly. For the camera to render, you must have attached the `XRVideoController` to your camera. Navigate to your project scene, click on `Main Camera`. Your `Inspector` pane should look something like this:
![screen shot 2018-09-09 at 7 06 32 pm](https://user-images.githubusercontent.com/2483955/45272718-c3878280-b463-11e8-9d76-0ea0f64e984a.png)


Lastly, do you see the table with the TV in your scene when you build your app, or is it just an empty Unity scene with the skybox?

**Comment by EunjeYu** [comment]
thank you for replying. 
all settings wall done. ( build setting - ios well switched
<img width="1305" alt="sample3" src="https://user-images.githubusercontent.com/22653847/45273886-a26c7380-b4ef-11e8-9785-1db43cb11f6d.png">
) 
and i attached screenshot my XRController's inspector. 
Can you help me?

**Comment by atomarch** [comment]
You are missing XRVideoController on your Main Camera

**Comment by EunjeYu** [comment]
oh.. ok the camera turns on now. sorry,, i thought video componenet just for recoding function..
Thank you!

**Comment by mralbean** [comment]
Awesome! Glad to hear everything is working! :)
