### ISSUE TITLE
Continous Image Detection with Move To

### ISSUE THREAD

**Issue by GimpMaster** [8thwall/xr-unity#71]
I've been playing a bit with the image detection on a Samsung S7. I'm working through a couple issues that I might report back on if I can't solve but.......

Using a simple cube, I can place it onto a detected image (poster I have laying horizontally) and that seems to work. I've followed your tutorial and it detects it and calls MoveTo() function. However I would like to be able to physically pick up that detected image and have the gameObject continually track the detected image. 

Is that possible?

**Comment by GimpMaster** [comment]
Ok, it does seem like it updates. It doesn't track very well. Is that expected? Should I expect to be able to pick up the poster and move it and watch the cube track with good precision?

**Comment by mralbean** [comment]
In this case, ARCore's image detection functionality is being used. As per the ARCore documentation, [ARCore cannot track a moving image, but it can resume tracking that image after it stops moving](https://developers.google.com/ar/develop/c/augmented-images/).

**Comment by GimpMaster** [comment]
Thank you @mralbean . It looks like its the same for iOS...however ios 12 should have image tracking support with ARKit 2.0.

https://medium.com/@ivannesterenko/image-tracking-with-arkit-2-0-d55dd6b556e7

Hopefully it won't be too long until it is in 8thwall as well.
