### ISSUE TITLE
NavMesh with XRController

### ISSUE THREAD

**Issue by GimpMaster** [8thwall/xr-unity#77]
Hello, I've got an AR level with some NavAgents. I've baked a NavMesh, using static objects, however the problem is static objects wont adjust with the XRController when it finds a surface. What are your suggestions in doing Path Navigation in AR when you have some fake walls you want the AI to avoid?

Thanks

**Comment by atomarch** [comment]
Great, glad you were able to resolve your issue, and thanks for sharing your solution!
