### ISSUE TITLE
Camera position is not changing

### ISSUE THREAD

**Issue by wilk3ns** [8thwall/xr-unity#8]
Hi!  I think there is a problem with XRController class. XRCameraController class cannot get reality camera position using XRController.GetCameraPosition() method. In every update the method resumes zero for all position variables. I tried to track down the source of the problem and then found that inside XRNativeBridge.cs under Android JNI there is a code like - 
r.ptr.cameraExtrinsicPositionX = jr.Call<float>("cameraExtrinsicPositionX");
r.ptr.cameraExtrinsicPositionY = jr.Call<float>("cameraExtrinsicPositionY");
r.ptr.cameraExtrinsicPositionZ = jr.Call<float>("cameraExtrinsicPositionZ");;

which is supposed to take camera extrinsic position data from native call.Then I tried to decompile com.the8thwall.reality.app.xr.android.XRAndroid.java file from provided jar executable which jr.Call takes variables from to see if there is anything about it but no luck. All java calls like jr.Call<float>("cameraExtrinsicPositionX") are returning zero. Please 8th Wall team fix this bug ASAP

Thanks in advance!

**Comment by wilk3ns** [comment]
@atomarch any idea? I'm using Nexus 6P running Android 8.0.0

**Comment by atomarch** [comment]
6DoF tracking is currently supported for Tango and ARKit enabled devices.  We are actively working to add 6DoF support to ARCore Android phones.  For all other phones, as of today we fall back to 3DoF tracking and fixed surfaces, which explains why the position variables are zero.  Our plan is to enhance this going forward.

**Comment by wilk3ns** [comment]
Okay it explains everything. But just for info, I learned about your SDK from ARCore forums in search of its port it on my Nexus 6P. somebody suggested that if your phone is not supporting ARCore then try 8th Wall XR. So I gave a try. Thanks a lot we appreciate your work!
