### ISSUE TITLE
AR scene doesn't Open in iPAD

### ISSUE THREAD

**Issue by trishika02** [8thwall/xr-unity#80]
![screen_shot_2018-11-25_at_5 06 15_pm](https://user-images.githubusercontent.com/35651199/49028808-764abf80-f1cd-11e8-8252-fa7aa6ab7c4f.png)
![screen_shot_2018-11-25_at_5 06 15_pm](https://user-images.githubusercontent.com/35651199/49028857-8f537080-f1cd-11e8-8234-23b75478e328.png)

Hello, I made an app with 8th wall for Android already, where i faced couple of problems but overcome after couple of try, NOW um trying to make the same app available for IOS, but end up with a problem,
The app was building successfully from Xcode BUT whenever i try to open unity scene with 8thwall XR it immediately kick me out of the app
Then i try to go for simple step to build only the sample scene from 8thwall, but the same problem happening again, here is the message Xcode shows when i try run the app while the IPAD plugged in with my MAC OS (xcode10)
Error Msg at line 33
Thread 1: signal SIGABRT
here is my IOS device and sdk configuration
1. IOS Device - iPAD 2, SDK Version 9.3.5 - Xcode 10 - High Sierra 10.13.6 (17G65)
2. Unity 2017.4 - 8th wall sdk 9.1
I attached the snapshot above.

**Comment by atomarch** [comment]
Hi @trishika02 , can you provide additional logs from your error?  A common cause of immediate app crashes in a missing or invalid app key.  Please check your Unity iOS project settings and make sure that the bundle identifier matches and your app key has been set in Assets -> XR -> 8th Wall XR

**Comment by trishika02** [comment]
thanks for ur reply. I checked the app key and bundle identifier and found nothing wrong. I am attaching the snapshot of them here for u. And about the logs from XCode, as i'm new to ios and xcode, I'm not sure where i would find the exact logs u asked for. YET I am attaching some LOG information that i found in xcode when i tried to run the app on my device.
![screen shot 2018-11-27 at 3 18 27 pm](https://user-images.githubusercontent.com/35651199/49077566-c7a68d80-f265-11e8-9a3e-6d7a968945c0.png)
![screen shot 2018-11-27 at 3 18 52 pm](https://user-images.githubusercontent.com/35651199/49077568-c83f2400-f265-11e8-89d2-1a2461dff9eb.png)`

**Comment by trishika02** [comment]
default	17:23:26.000000 +055320	SpringBoard	  SecTrustEvaluate  [leaf IssuerCommonName SubjectCommonName]

default	17:23:26.000000 +055320	SpringBoard	  SecTrustEvaluate  [leaf IssuerCommonName SubjectCommonName]

default	18:23:26.000000 +055320	kernel	 xpcproxy[2000] Container: /private/var/mobile/Containers/Data/Application/013FA269-1015-4587-9768-574DC526B57F (sandbox)

default	17:23:26.000000 +055320	com.apple.xpc.launchd	 assertion failed: 13G36: launchd + 85529 [083E000D-4C31-3B98-A2C4-6FADB4D1940F]: 0x3

default	17:23:26.000000 +055320	ios	 -> registered mono modules 0xd5c910

default	18:23:26.000000 +055320	ios	 Internal error unloading bundle CFBundle 0x16dc55d0 </System/Library/Frameworks/Metal.framework> (loaded)

default	18:23:27.000000 +055320	ios	 Renderer: PowerVR SGX 543

default	18:23:27.000000 +055320	ios	 Vendor:   Imagination Technologies

default	18:23:27.000000 +055320	ios	 Version:  OpenGL ES 2.0 IMGSGX543-124.1

default	18:23:27.000000 +055320	ios	 GLES:     2

default	17:23:27.000000 +055320	ios	 GL_OES_depth_texture GL_OES_depth24 GL_OES_element_index_uint GL_OES_fbo_render_mipmap GL_OES_mapbuffer GL_OES_packed_depth_stencil GL_OES_rgb8_rgba8 GL_OES_standard_derivatives GL_OES_texture_float GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_OES_vertex_array_object GL_EXT_blend_minmax GL_EXT_color_buffer_half_float GL_EXT_debug_label GL_EXT_debug_marker GL_EXT_discard_framebuffer GL_EXT_draw_instanced GL_EXT_instanced_arrays GL_EXT_map_buffer_range GL_EXT_occlusion_query_boolean GL_EXT_pvrtc_sRGB GL_EXT_read_format_bgra GL_EXT_separate_shader_objects GL_EXT_shader_framebuffer_fetch GL_EXT_shader_texture_lod GL_EXT_shadow_samplers GL_EXT_sRGB GL_EXT_texture_filter_anisotropic GL_EXT_texture_rg GL_EXT_texture_storage GL_APPLE_clip_distance GL_APPLE_color_buffer_packed_float GL_APPLE_copy_texture_levels GL_APPLE_framebuffer_multisample GL_APPLE_rgb_422 GL_APPLE_sync GL_APPLE_texture_format_BGRA8888 GL_APPLE_texture_max_level GL_APPLE_texture_packed_float GL_IMG_read_format GL_IMG_texture_comp

default	17:23:27.000000 +055320	ios	 ression_pvrtc 

default	18:23:27.000000 +055320	ios	 OPENGL LOG: Creating OpenGL ES 2.0 graphics device ; Context level  <OpenGL ES 2.0> ; Context handle 383345824

default	18:23:27.000000 +055320	ios	 Initialize engine version: 2017.4.16f1 (7f7bdd1ef02b)

default	18:23:27.000000 +055320	ios	 WARNING: 0:4: extension 'GL_EXT_frag_depth' is not supported
	ERROR: 0:38: Use of undeclared identifier 'gl_FragDepthEXT'

default	17:23:27.000000 +0600	ios	 Note: Creation of internal variant of shader 'Hidden/Internal-MotionVectors' failed.

default	18:23:27.000000 +0600	ios	 WARNING: Shader 

default	18:23:27.000000 +055320	ios	 Unsupported: 'Hidden/Internal-MotionVectors' - Pass '' has no vertex shader

default	18:23:27.000000 +055320	ios	 WARNING: Shader 

default	18:23:27.000000 +055320	ios	 Unsupported: 'Hidden/Internal-MotionVectors' - Setting to default shader.

default	17:23:27.000000 +055320	ios	 WARNING: Shader 

default	18:23:27.000000 +055320	ios	 Unsupported: 'Unlit/ARCoreCameraShader' - Pass '' has no vertex shader

default	18:23:27.000000 +055320	ios	 WARNING: Shader 

default	18:23:27.000000 +055320	ios	 Unsupported: 'Unlit/ARCoreTextureShader' - Pass '' has no vertex shader

default	18:23:27.000000 +055320	ios	 WARNING: Shader 

default	18:23:27.000000 +055320	ios	 Unsupported: 'Hidden/BlitToDepth' - Pass '' has no vertex shader

default	18:23:27.000000 +055320	ios	 WARNING: Shader 

default	18:23:27.000000 +055320	ios	 Unsupported: 'Hidden/BlitToDepth' - Setting to default shader.

default	18:23:27.000000 +055320	ios	 WARNING: Shader 

default	18:23:27.000000 +055320	ios	 Unsupported: 'Hidden/BlitToDepth_MSAA' - Pass '' has no vertex shader

default	18:23:27.000000 +055320	ios	 WARNING: Shader 

default	18:23:27.000000 +055320	ios	 Unsupported: 'Hidden/BlitToDepth_MSAA' - Setting to default shader.

default	18:23:27.000000 +055320	ios	 WARNING: 0:4: extension 'GL_EXT_frag_depth' is not supported
	ERROR: 0:14: Use of undeclared identifier 'gl_FragDepthEXT'

default	18:23:27.000000 +055320	ios	 Note: Creation of internal variant of shader 'Hidden/BlitCopyWithDepth' failed.

default	18:23:27.000000 +055320	ios	 WARNING: Shader 

default	18:23:27.000000 +055320	ios	 Unsupported: 'Hidden/BlitCopyWithDepth' - Pass '' has no vertex shader

default	18:23:27.000000 +055320	ios	 WARNING: Shader 

default	18:23:27.000000 +055320	ios	 Unsupported: 'Hidden/BlitCopyWithDepth' - Setting to default shader.

default	17:23:29.000000 +055320	ios	 UnloadTime: 8.009125 ms

default	17:23:29.000000 +0600	ios	 OnGUI function detected on MonoBehaviour, but not called, because IMGUI module is stripped.

default	18:23:29.000000 +055320	mediaserverd	 '' com.zoetrope.ios(pid = 2000) setting DiscoveryMode = DiscoveryMode_None, currentDiscoveryMode = DiscoveryMode_None

default	18:23:29.000000 +055320	kernel	 AppleH4CamIn::setPowerStateGated: 1

default	18:23:29.000000 +055320	kernel	 AppleH4CamIn::power_on_hardware

default	17:23:30.000000 +055320	ios	 Uncaught exception: NSInvalidArgumentException: *** -[AVCaptureVideoDevice setFocusMode:] - the passed focusMode 1 is not supported by the device.  Use -isFocusModeSupported: to discover valid focus modes.
	(
		0   CoreFoundation                      0x2512f933 <redacted> + 150
		1   libobjc.A.dylib                     0x248cae17 objc_exception_throw + 38
		2   AVFoundation                        0x2aacaac9 <redacted> + 352
		3   ios                                 0x00a89e1d -[CameraSensorImpl setCameraAutofocus:] + 312
		4   ios                                 0x00a88d87 -[CameraSensorImpl configure:] + 422
		5   ios                                 0x00a8a4ad c8CameraSensor_configure + 22
		6   ios                                 0x00a88157 _ZN2c87XRIosC89configureENS_15XRConfiguration6ReaderEPNS_14LoggingContextE + 76
		7   ios                                 0x00a7b9df _ZN2c85XRIos9configureENS_15XRConfiguration6ReaderE + 978
		8   ios                                 0x00a7fddd c8XRIos_configureXR + 156
		9   ios                                 0x000d050f XRNativeBridge_XRConfigure_m4250090790 + 32
		10  ios                                 0x000c9683 XRController_ConfigureXR_m3140832430 + 754
		11  ios                                 0x000c8a47 XRCameraController_OnEnable_m2073887656 + 234
		12  ios                                 0x003498dd _Z31RuntimeInvoker_Void_t1185182177PFvvEPK10MethodInfoPvPS4_ + 10
		13  ios                                 0x00a72127 _ZN6il2cpp2vm7Runtime6InvokeEPK10MethodInfoPvPS5_PP15Il2CppException + 118
		14  ios                                 0x005a344f _Z23scripting_method_invoke18ScriptingMethodPtr18ScriptingObjectPtrR18ScriptingArgumentsP21ScriptingExceptionPtrb + 66
		15  ios                                 0x005a98ad _ZN19ScriptingInvocation6InvokeEP21ScriptingExceptionPtrb + 38
		16  ios                                 0x005aebc3 _ZN13MonoBehaviour12AddToManagerEv + 200
		17  ios                                 0x005ae925 _ZN13MonoBehaviour13AwakeFromLoadE17AwakeFromLoadMode + 390
		18  ios                                 0x005d50f7 _ZN18AwakeFromLoadQueue28InvokePersistentManagerAwakeEPNS_4ItemEj17AwakeFromLoadMode + 214
		19  ios                                 0x005d4fcd _ZN18AwakeFromLoadQueue30PersistentManagerAwakeFromLoadEi17AwakeFromLoadMode + 92
		20  ios                                 0x005d4f69 _ZN18AwakeFromLoadQueue30PersistentManagerAwakeFromLoadEv + 18
		21  ios                                 0x005277c7 _ZN18LoadSceneOperation21CompleteAwakeSequenceEv + 70
		22  ios                                 0x00527807 _ZN18LoadSceneOperation31CompletePreloadManagerLoadSceneEv + 24
		23  ios                                 0x0052738d _ZN18LoadSceneOperation25PlayerLoadSceneFromThreadEv + 356
		24  ios                                 0x00527489 _ZN18LoadSceneOperation22CompleteLoadFirstSceneEv + 8
		25  ios                                 0x00527151 _ZN18LoadSceneOperation19IntegrateMainThreadEv + 80
		26  ios                                 0x0052800b _ZN14PreloadManager26UpdatePreloadingSingleStepENS_21UpdatePreloadingFlagsEi + 274
		27  ios                                 0x0052867d _ZN14PreloadManager16UpdatePreloadingEv + 276
		28  ios                                 0x00504e9b _Z10PlayerLoopv + 410
		29  ios                                 0x0038e37d _ZL19UnityPlayerLoopImplb + 22
		30  ios                                 0x000b14c1 UnityRepaint + 220
		31  ios                                 0x000b1379 -[UnityAppController(Rendering) repaintDisplayLink] + 76
		32  QuartzCore                          0x2778ba0b <redacted> + 106
		33  QuartzCore                          0x2778b857 <redacted> + 594
		34  IOMobileFramebuffer                 0x26e7250b <redacted> + 86
		35  IOKit                               0x25380759 IODispatchCalloutFromCFMessage + 256
		36  CoreFoundation                      0x250de37d <redacted> + 132
		37  CoreFoundation                      0x250f25b3 <redacted> + 34
		38  CoreFoundation                      0x250f1cc7 <redacted> + 342
		39  CoreFoundation                      0x250f00d9 <redacted> + 1688
		40  CoreFoundation                      0x2503f229 CFRunLoopRunSpecific + 520
		41  CoreFoundation                      0x2503f015 CFRunLoopRunInMode + 108
		42  GraphicsServices                    0x2662fac9 GSEventRunModal + 160
		43  UIKit                               0x29713189 UIApplicationMain + 144
		44  ios                                 0x000a871f main + 206
		45  libdyld.dylib                       0x24ce7873 <redacted> + 2
	)

default	17:23:30.000000 +055320	ios	 *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[AVCaptureVideoDevice setFocusMode:] - the passed focusMode 1 is not supported by the device.  Use -isFocusModeSupported: to discover valid focus modes.'
	*** First throw call stack:
	(0x2512f91b 0x248cae17 0x2aacaac9 0xa89e1d 0xa88d87 0xa8a4ad 0xa88157 0xa7b9df 0xa7fddd 0xd050f 0xc9683 0xc8a47 0x3498dd 0xa72127 0x5a344f 0x5a98ad 0x5aebc3 0x5ae925 0x5d50f7 0x5d4fcd 0x5d4f69 0x5277c7 0x527807 0x52738d 0x527489 0x527151 0x52800b 0x52867d 0x504e9b 0x38e37d 0xb14c1 0xb1379 0x2778ba0b 0x2778b857 0x26e7250b 0x25380759 0x250de37d 0x250f25b3 0x250f1cc7 0x250f00d9 0x2503f229 0x2503f015 0x2662fac9 0x29713189 0xa871f 0x24ce7873)

default	18:23:30.000000 +055320	SpringBoard	 HW kbd: Failed to set (null) as keyboard focus

default	18:23:30.000000 +055320	mediaserverd	 '' com.zoetrope.ios(pid = 2000) setting DiscoveryMode = DiscoveryMode_None, currentDiscoveryMode = DiscoveryMode_None

default	18:23:30.000000 +055320	mediaserverd	 '' (pid = 2000) setting DiscoveryMode = DiscoveryMode_None, currentDiscoveryMode = DiscoveryMode_None

default	17:23:30.000000 +055320	mediaserverd	 '' com.zoetrope.ios(pid = 2000) setting DiscoveryMode = DiscoveryMode_None, currentDiscoveryMode = DiscoveryMode_None

default	18:23:30.000000 +055320	com.apple.xpc.launchd	 Service exited due to signal: Abort trap: 6

default	18:23:30.000000 +055320	SpringBoard	 Application 'UIKitApplication:com.zoetrope.ios[0xc4b8]' crashed.

default	18:23:30.000000 +055320	UserEventAgent	 5550873515249: id=com.zoetrope.ios pid=2000, state=0

default	18:23:30.000000 +055320	ReportCrash	 assertion failed: 13G36: libsystem_trace.dylib + 15927 [E82A6F2D-873A-39AD-8014-EDEB52248157]: 0x0

default	18:23:30.000000 +055320	Unknown	 

default	18:23:30.000000 +055320	ReportCrash	 os_activity_diagnostic_for_pid() failed!

default	18:23:30.000000 +055320	ReportCrash	 Formulating report for corpse[2000] ios

default	18:23:30.000000 +055320	ReportCrash	 Saved type '109(109_ios)' report (11 of max 25) at /var/mobile/Library/Logs/CrashReporter/ios-2018-11-27-182330.ips

default	17:23:34.000000 +055320	kernel	 AppleH4CamIn::setPowerStateGated: 0

default	17:23:34.000000 +055320	kernel	 AppleH4CamIn::power_off_hardware

**Comment by trishika02** [comment]
2018-11-27 18:06:58.784 ios[1931:559760] -> registered mono modules 0xd1e910
-> applicationDidFinishLaunching()
2018-11-27 18:06:59.068 ios[1931:559760] Metal GPU Frame Capture Enabled
2018-11-27 18:06:59.069 ios[1931:559760] Metal API Validation Disabled
-> applicationDidBecomeActive()
Renderer: PowerVR SGX 543
Vendor:   Imagination Technologies
Version:  OpenGL ES 2.0 IMGSGX543-124.1
GLES:     2
GL_OES_depth_texture GL_OES_depth24 GL_OES_element_index_uint GL_OES_fbo_render_mipmap GL_OES_mapbuffer GL_OES_packed_depth_stencil GL_OES_rgb8_rgba8 GL_OES_standard_derivatives GL_OES_texture_float GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_OES_vertex_array_object GL_EXT_blend_minmax GL_EXT_color_buffer_half_float GL_EXT_debug_label GL_EXT_debug_marker GL_EXT_discard_framebuffer GL_EXT_draw_instanced GL_EXT_instanced_arrays GL_EXT_map_buffer_range GL_EXT_occlusion_query_boolean GL_EXT_pvrtc_sRGB GL_EXT_read_format_bgra GL_EXT_separate_shader_objects GL_EXT_shader_framebuffer_fetch GL_EXT_shader_texture_lod GL_EXT_shadow_samplers GL_EXT_sRGB GL_EXT_texture_filter_anisotropic GL_EXT_texture_rg GL_EXT_texture_storage GL_APPLE_clip_distance GL_APPLE_color_buffer_packed_float GL_APPLE_copy_texture_levels GL_APPLE_framebuffer_multisample GL_APPLE_rgb_422 GL_APPLE_sync GL_APPLE_texture_format_BGRA8888 GL_APPLE_texture_max_level GL_APPLE_texture_packed_float GL_IMG_read_format GL_IMG_texture_comp

ression_pvrtc 
OPENGL LOG: Creating OpenGL ES 2.0 graphics device ; Context level  <OpenGL ES 2.0> ; Context handle 392304096
Initialize engine version: 2017.4.16f1 (7f7bdd1ef02b)
WARNING: 0:4: extension 'GL_EXT_frag_depth' is not supported
ERROR: 0:38: Use of undeclared identifier 'gl_FragDepthEXT'

Note: Creation of internal variant of shader 'Hidden/Internal-MotionVectors' failed.
WARNING: Shader Unsupported: 'Hidden/Internal-MotionVectors' - Pass '' has no vertex shader
WARNING: Shader Unsupported: 'Hidden/Internal-MotionVectors' - Setting to default shader.
WARNING: Shader Unsupported: 'Unlit/ARCoreCameraShader' - Pass '' has no vertex shader
WARNING: Shader Unsupported: 'Unlit/ARCoreTextureShader' - Pass '' has no vertex shader
WARNING: Shader Unsupported: 'Hidden/BlitToDepth' - Pass '' has no vertex shader
WARNING: Shader Unsupported: 'Hidden/BlitToDepth' - Setting to default shader.
WARNING: Shader Unsupported: 'Hidden/BlitToDepth_MSAA' - Pass '' has no vertex shader
WARNING: Shader Unsupported: 'Hidden/BlitToDepth_MSAA' - Setting to default shader.
WARNING: 0:4: extension 'GL_EXT_frag_depth' is not supported
ERROR: 0:14: Use of undeclared identifier 'gl_FragDepthEXT'

Note: Creation of internal variant of shader 'Hidden/BlitCopyWithDepth' failed.
WARNING: Shader Unsupported: 'Hidden/BlitCopyWithDepth' - Pass '' has no vertex shader
WARNING: Shader Unsupported: 'Hidden/BlitCopyWithDepth' - Setting to default shader.
UnloadTime: 7.555500 ms
OnGUI function detected on MonoBehaviour, but not called, because IMGUI module is stripped.
2018-11-27 18:07:02.986 ios[1931:559760] Uncaught exception: NSInvalidArgumentException: *** -[AVCaptureVideoDevice setFocusMode:] - the passed focusMode 1 is not supported by the device.  Use -isFocusModeSupported: to discover valid focus modes.
(
	0   CoreFoundation                      0x2512f933 <redacted> + 150
	1   libobjc.A.dylib                     0x248cae17 objc_exception_throw + 38
	2   AVFoundation                        0x2aacaac9 <redacted> + 352
	3   ios                                 0x00a4be1d -[CameraSensorImpl setCameraAutofocus:] + 312
	4   ios                                 0x00a4ad87 -[CameraSensorImpl configure:] + 422
	5   ios                                 0x00a4c4ad c8CameraSensor_configure + 22
	6   ios                                 0x00a4a157 _ZN2c87XRIosC89configureENS_15XRConfiguration6ReaderEPNS_14LoggingContextE + 76
	7   ios                                 0x00a3d9df _ZN2c85XRIos9configureENS_15XRConfiguration6ReaderE + 978
	8   ios                                 0x00a41ddd c8XRIos_configureXR + 156
	9   ios                                 0x0009250f XRNativeBridge_XRConfigure_m4250090790 + 32
	10  ios                                 0x0008b683 XRController_ConfigureXR_m3140832430 + 754
	11  ios                                 0x0008aa47 XRCameraController_OnEnable_m2073887656 + 234
	12  ios                                 0x0030b8dd _Z31RuntimeInvoker_Void_t1185182177PFvvEPK10MethodInfoPvPS4_ + 10
	13  ios                                 0x00a34127 _ZN6il2cpp2vm7Runtime6InvokeEPK10MethodInfoPvPS5_PP15Il2CppException + 118
	14  ios                                 0x0056544f _Z23scripting_method_invoke18ScriptingMethodPtr18ScriptingObjectPtrR18ScriptingArgumentsP21ScriptingExceptionPtrb + 66
	15  ios                                 0x0056b8ad _ZN19ScriptingInvocation6InvokeEP21ScriptingExceptionPtrb + 38
	16  ios                                 0x00570bc3 _ZN13MonoBehaviour12AddToManagerEv + 200
	17  ios                                 0x00570925 _ZN13MonoBehaviour13AwakeFromLoadE17AwakeFromLoadMode + 390
	18  ios                                 0x005970f7 _ZN18AwakeFromLoadQueue28InvokePersistentManagerAwakeEPNS_4ItemEj17AwakeFromLoadMode + 214
	19  ios                                 0x00596fcd _ZN18AwakeFromLoadQueue30PersistentManagerAwakeFromLoadEi17AwakeFromLoadMode + 92
	20  ios                                 0x00596f69 _ZN18AwakeFromLoadQueue30PersistentManagerAwakeFromLoadEv + 18
	21  ios                                 0x004e97c7 _ZN18LoadSceneOperation21CompleteAwakeSequenceEv + 70
	22  ios                                 0x004e9807 _ZN18LoadSceneOperation31CompletePreloadManagerLoadSceneEv + 24
	23  ios                                 0x004e938d _ZN18LoadSceneOperation25PlayerLoadSceneFromThreadEv + 356
	24  ios                                 0x004e9489 _ZN18LoadSceneOperation22CompleteLoadFirstSceneEv + 8
	25  ios                                 0x004e9151 _ZN18LoadSceneOperation19IntegrateMainThreadEv + 80
	26  ios                                 0x004ea00b _ZN14PreloadManager26UpdatePreloadingSingleStepENS_21UpdatePreloadingFlagsEi + 274
	27  ios                                 0x004ea67d _ZN14PreloadManager16UpdatePreloadingEv + 276
	28  ios                                 0x004c6e9b _Z10PlayerLoopv + 410
	29  ios                                 0x0035037d _ZL19UnityPlayerLoopImplb + 22
	30  ios                                 0x000734c1 UnityRepaint + 220
	31  ios                                 0x00073379 -[UnityAppController(Rendering) repaintDisplayLink] + 76
	32  libMTLInterpose.dylib               0x02132865 -[DYDisplayLinkInterposer forwardDisplayLinkCallback:] + 276
	33  QuartzCore                          0x2778ba0b <redacted> + 106
	34  QuartzCore                          0x2778b857 <redacted> + 594
	35  IOMobileFramebuffer                 0x26e7250b <redacted> + 86
	36  IOKit                               0x25380759 IODispatchCalloutFromCFMessage + 256
	37  CoreFoundation                      0x250de37d <redacted> + 132
	38  CoreFoundation                      0x250f25b3 <redacted> + 34
	39  CoreFoundation                      0x250f1cc7 <redacted> + 342
	40  CoreFoundation                      0x250f00d9 <redacted> + 1688
	41  CoreFoundation                      0x2503f229 CFRunLoopRunSpecific + 520
	42  CoreFoundation                      0x2503f015 CFRunLoopRunInMode + 108
	43  GraphicsServices                    0x2662fac9 GSEventRunModal + 160
	44  UIKit                               0x29713189 UIApplicationMain + 144
	45  ios                                 0x0006a71f main + 206
	46  libdyld.dylib                       0x24ce7873 <redacted> + 2
)
2018-11-27 18:07:02.991 ios[1931:559760] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[AVCaptureVideoDevice setFocusMode:] - the passed focusMode 1 is not supported by the device.  Use -isFocusModeSupported: to discover valid focus modes.'
*** First throw call stack:
(0x2512f91b 0x248cae17 0x2aacaac9 0xa4be1d 0xa4ad87 0xa4c4ad 0xa4a157 0xa3d9df 0xa41ddd 0x9250f 0x8b683 0x8aa47 0x30b8dd 0xa34127 0x56544f 0x56b8ad 0x570bc3 0x570925 0x5970f7 0x596fcd 0x596f69 0x4e97c7 0x4e9807 0x4e938d 0x4e9489 0x4e9151 0x4ea00b 0x4ea67d 0x4c6e9b 0x35037d 0x734c1 0x73379 0x2132865 0x2778ba0b 0x2778b857 0x26e7250b 0x25380759 0x250de37d 0x250f25b3 0x250f1cc7 0x250f00d9 0x2503f229 0x2503f015 0x2662fac9 0x29713189 0x6a71f 0x24ce7873)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by mralbean** [comment]
Fixed in Release 9.2. Closing this out.
