### ISSUE TITLE
how to get image size return from image detection

### ISSUE THREAD

**Issue by tissueme** [8thwall/xr-unity#81]
I need to use size of image from image detection to make my sprite fit that image.
have any idea? 

> public void MoveToTarget(XRDetectedImageTarget target)
    {
        transform.position = target.position;
        testTxt.text = "W : " + target.width.ToString() + " H : " + target.height.ToString();
    }

target.width it return in unity units not pixels

Sorry for my bad english skills

**Comment by dattanchu** [comment]
Can you describe more what you are trying to achieve? Can you put your sprite on a Unity GameObject that can use the transform and sizing that XRDetectedImageTarget give?

**Comment by tissueme** [comment]
hello @dattanchu thank for reply.
now i can solve this problem by using UI component sizedelta
Thanks.
