### ISSUE TITLE
Issues with Enabling/Disabling XRVideoController fast

### ISSUE THREAD

**Issue by GimpMaster** [8thwall/xr-unity#86]
I recently came across an issue where I had the XRVideoController Enabled. It successfully saved off the Skybox clear flags and enabled the Depth clear flag with video. All was AR as normal.

Then later on I disabled the XRVideoController which restored the Skybox clear flag. Still all good.

Finally I had some logic that re-enabled XRVideoController, but then disabled it again in the same frame.

The issue was the following...

 void OnEnable() {
    // did we get re-enabled after disabled?
    if (initialized) {
      camOriginalClearFlag_ = cam.clearFlags;
      cam.clearFlags = CameraClearFlags.Depth;
    }
  }

initialized == true, so it set the cam.clearFlags to Depth. But since OnPreRender() didn't get called yet. When we got to OnDisable() below...

 void OnDisable() {
    if (isCBInit) {
      cam.RemoveCommandBuffer(CameraEvent.BeforeForwardOpaque, buffer);
      cam.clearFlags = camOriginalClearFlag_;
      isCBInit = false;
    }
  }

isCBInit = false. Which meant my clearFlags were stuck now on Depth mode but with no camera feed.

Now obviously I fixed this by not doing something as dumb as enable/disable really fast, but I figured I would let you know about this corner case.

**Comment by atomarch** [comment]
@GimpMaster, to follow up on the slack discussion (https://8thwalldevs.slack.com/archives/CB4FV2N58/p1550039710012300) this is related to a change Unity made in 2018.3 - camera permissions are no longer requested automatically on Android devices.  We added an option to XRController in R10 handle this for you, however, we then found that ARCore was still trying to access the camera even prior to our request.  This only affects apps that open *directly* to the camera, and the first time only.  Release 10.1 (which is currently on our beta channel) has an additional fix for this.  

You can switch to the beta channel within Unity and test it out for yourself.  Should no longer need a “restart your app” dialog: https://docs.8thwall.com/xr/#switching-channels .

More info on how Android permissions are handled in Unity 2018.3+: https://docs.8thwall.com/xr/#unity-2018-doesnt-ask-for-android-camera-permissions
