### ISSUE TITLE
Object spawning behind the camera.

### ISSUE THREAD

**Issue by viknesh2020** [8thwall/xr-unity#89]
I have a scene in which the XRSurfaceController is attached to an empty gameobject and a prefab is attached to it as a child object. Everytime I start the app and show my camera on table surface, the object spawns behind my camera and not on the surface. I have to walk reverse to see my object in the camera. Why it is like this? 

I am using Nexus 6, which doesn't support ARCore. Checked all the options in XRSurfaceController, enabled and disabled Lock to first surface, Ground only. Tried all but still the object spawns in the same way.

Need your points asap.

**Comment by viknesh2020** [comment]
I myself searched for a solution and found the following in your documentation
https://docs.8thwall.com/xr/#6dof-camera-motion-not-working-on-non-arkitnon-arcore-devices

Here it says, for Non-AR Core/ARKit devices, the object spawning is completely related to the camera position that we set in the scene. There is nothing to be done with Surface Detection for these devices. I have done what is given in that link and still the object is not spawning in the middle of the camera. My camera preview looks as I wanted but when I build the app, the object is below or behind my phone.

**Comment by atomarch** [comment]
Can you share additional screenshots on your scene setup?  Specifically, I'd like to see inspector details and camera preview window for the main camera.  Also, the object which has XRSurfaceController attached, as well as your child object.  (Note: typically XRSurfaceController is attached to a 3D plane game object - with our XRTransparentSurface material and your game objects would be a child of that)

**Comment by viknesh2020** [comment]
Hi! Thank you for the reply. 
![XRSurface](https://user-images.githubusercontent.com/39415878/56466742-32ce4780-6433-11e9-98a3-e8737ee33805.JPG)
![Camera_Inspector](https://user-images.githubusercontent.com/39415878/56466743-3366de00-6433-11e9-8d37-70246c8ab2b7.JPG)
![Gameobject_Inspector](https://user-images.githubusercontent.com/39415878/56466744-3366de00-6433-11e9-8026-0f137d9bd65c.JPG)
![SceneView_CameraPreview](https://user-images.githubusercontent.com/39415878/56466746-3366de00-6433-11e9-8fc4-0009300d861e.JPG)
![XRController](https://user-images.githubusercontent.com/39415878/56466747-3366de00-6433-11e9-9840-dfd9cf0348d8.JPG)

See the screenshots attached for your review. Sometimes the object is not stable. It is vanishing from the screen.

**Comment by atomarch** [comment]
On your XRSurfaceController, try enabling "display immediately"

**Comment by viknesh2020** [comment]
> On your XRSurfaceController, try enabling "display immediately"

I remember trying it once, but anyhow let me check once again. Thank you

**Comment by viknesh2020** [comment]
Display immediately did not solve the issue. Howver, I changed the camera position and the object's position. Also changed the scale value in the XRCameraController solved the issue. Thank you.
