### ISSUE TITLE
Missing prefab in example 

### ISSUE THREAD

**Issue by fountainYuan** [8thwall/xr-unity#9]
I add example in Unity3D projects, but  display "Missing prefab", table in the scene and TV disppeared.

**Comment by halabo** [comment]
hi,i think you should install a [blender](https://www.blender.org/) before you import the sample package into the unity .

**Comment by halabo** [comment]
hi,i think you should install a [blender](https://www.blender.org) before you import the sample package into the unity .

**Comment by atomarch** [comment]
Hi @fountainYuan , thanks for reporting this issue.  @halabo is correct, the Table prefab is a .blend file and installation of blender would fix this.  I have just regenerated the project and replaced the .blend with an .fbx file.  If you grab the latest version it should work for you now.
