### ISSUE TITLE
MoveToTarget Not Workin

### ISSUE THREAD

**Issue by vxrlc** [8thwall/xr-unity#91]
I'm able to get the image to be detected and the MoveToTarget is fired, but it doesn't seem to "anchor" the object on to the image?  The object does move, but it doesn't move to the target's location.

**Comment by atomarch** [comment]
What type of device are you using?  Image detection in Unity currently requires an ARKit/ARCore capable device.  Please see https://docs.8thwall.com/xr/#features-supported-by-platform

If you are using an device with ARKit/ARCore, please share additional details on your scene setup.  Properly defining the width in meters is important for proper placement. ARKit/ARCore use this to determine how far from the camera the detected image is.
